// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.example.lab;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_lab_VideoIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_lab_VideoIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_lab_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_lab_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_lab_UploadVideoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_lab_UploadVideoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_lab_Creator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_lab_Creator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_lab_CreatorIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_lab_CreatorIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_lab_VideoStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_lab_VideoStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\017org.example.lab\"\034\n\016Video" +
      "IdRequest\022\n\n\002id\030\001 \001(\t\"\211\001\n\005Video\022\n\n\002id\030\001 " +
      "\001(\t\022\r\n\005title\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022" +
      "\013\n\003url\030\004 \001(\t\022\030\n\020duration_seconds\030\005 \001(\005\022)" +
      "\n\007creator\030\006 \001(\0132\030.org.example.lab.Creato" +
      "r\"\212\001\n\022UploadVideoRequest\022\r\n\005title\030\001 \001(\t\022" +
      "\023\n\013description\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\022\030\n\020dur" +
      "ation_seconds\030\004 \001(\005\022)\n\007creator\030\005 \001(\0132\030.o" +
      "rg.example.lab.Creator\"2\n\007Creator\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"\036\n\020Cr" +
      "eatorIdRequest\022\n\n\002id\030\001 \001(\t\"5\n\013VideoStrea" +
      "m\022&\n\006videos\030\001 \003(\0132\026.org.example.lab.Vide" +
      "o2\260\001\n\016CreatorService\022I\n\ngetCreator\022!.org" +
      ".example.lab.CreatorIdRequest\032\030.org.exam" +
      "ple.lab.Creator\022S\n\020getCreatorVideos\022!.or" +
      "g.example.lab.CreatorIdRequest\032\034.org.exa" +
      "mple.lab.VideoStream2\237\001\n\014VideoService\022J\n" +
      "\013uploadVideo\022#.org.example.lab.UploadVid" +
      "eoRequest\032\026.org.example.lab.Video\022C\n\010get" +
      "Video\022\037.org.example.lab.VideoIdRequest\032\026" +
      ".org.example.lab.VideoB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_lab_VideoIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_lab_VideoIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_lab_VideoIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_org_example_lab_Video_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_lab_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_lab_Video_descriptor,
        new java.lang.String[] { "Id", "Title", "Description", "Url", "DurationSeconds", "Creator", });
    internal_static_org_example_lab_UploadVideoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_lab_UploadVideoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_lab_UploadVideoRequest_descriptor,
        new java.lang.String[] { "Title", "Description", "Url", "DurationSeconds", "Creator", });
    internal_static_org_example_lab_Creator_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_lab_Creator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_lab_Creator_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
    internal_static_org_example_lab_CreatorIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_example_lab_CreatorIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_lab_CreatorIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_org_example_lab_VideoStream_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_example_lab_VideoStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_lab_VideoStream_descriptor,
        new java.lang.String[] { "Videos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
