// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.example.lab;

public interface VideoStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.lab.VideoStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.lab.Video videos = 1;</code>
   */
  java.util.List<org.example.lab.Video> 
      getVideosList();
  /**
   * <code>repeated .org.example.lab.Video videos = 1;</code>
   */
  org.example.lab.Video getVideos(int index);
  /**
   * <code>repeated .org.example.lab.Video videos = 1;</code>
   */
  int getVideosCount();
  /**
   * <code>repeated .org.example.lab.Video videos = 1;</code>
   */
  java.util.List<? extends org.example.lab.VideoOrBuilder> 
      getVideosOrBuilderList();
  /**
   * <code>repeated .org.example.lab.Video videos = 1;</code>
   */
  org.example.lab.VideoOrBuilder getVideosOrBuilder(
      int index);
}
